/* Stockly: local-first inventory management */
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='stockly_v1';
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{products:[],sales:[],settings:{currency:'$',dark:false}};
let charts={};
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const money=n=>`${db.settings.currency==='MMK'?'MMK ':db.settings.currency}${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const dateStr=d=>new Date(d).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
const today=()=>new Date().toISOString().slice(0,10);
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function productById(id){return db.products.find(p=>p.id===id)}
function calc(){let revenue=db.sales.reduce((a,s)=>a+s.revenue,0),profit=db.sales.reduce((a,s)=>a+s.profit,0),qty=db.products.reduce((a,p)=>a+p.stock,0);return{revenue,profit,qty,low:db.products.filter(p=>p.stock>0&&p.stock<=5),out:db.products.filter(p=>p.stock===0)}}
function status(p){return p.stock===0?'out':p.stock<=5?'low':'healthy'}
function nav(page){$$('.page').forEach(x=>x.classList.toggle('active',x.id===page));$$('.nav-link[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#pageTitle').textContent=page==='dashboard'?'Good morning, Shane':({products:'Products',sales:'Sales management',inventory:'Inventory monitor',daily:'Daily report',monthly:'Monthly report',settings:'Settings'}[page]);$('#sidebar').classList.remove('open');render();window.scrollTo(0,0)}
function renderStats(){let c=calc(),data=[['Total products',db.products.length,'◈','var(--primary)'],['Stock quantity',c.qty,'▦','var(--green)'],['Total revenue',money(c.revenue),'↗','var(--primary2)'],['Total profit',money(c.profit),'◉','var(--green)'],['Low stock',c.low.length,'!','var(--orange)'],['Out of stock',c.out.length,'×','var(--red)']];$('#dashboardStats').innerHTML=data.map(x=>`<div class="stat-card" style="--stat-color:${x[3]}"><span class="stat-icon">${x[2]}</span><div class="stat-label">${x[0]}</div><div class="stat-value">${x[1]}</div></div>`).join('')}
function renderDashboard(){renderStats();let c=calc(),alerts=[...c.out,...c.low];$('#alertList').innerHTML=alerts.length?alerts.slice(0,5).map(p=>`<div class="alert-item ${status(p)}"><span class="alert-symbol">${p.stock?'!':'×'}</span><div><strong>${esc(p.name)}</strong><small>${p.stock?'Only '+p.stock+' left':'Restock required'}</small></div><span class="badge ${status(p)}">${p.stock?'Low':'Out'}</span></div>`).join(''):'<p class="empty">All products have healthy stock.</p>';$('#recentSales').innerHTML=db.sales.slice().reverse().slice(0,5).map(s=>`<tr><td class="product-name">${esc(s.productName)}</td><td class="muted">${esc(s.customer||'Walk-in')}</td><td>${s.quantity}</td><td>${money(s.revenue)}</td><td class="muted">${dateStr(s.date)}</td></tr>`).join('')||emptyRow(5,'No sales recorded yet.');makeChart('overviewChart',daysData().labels,daysData().revenue,'Revenue', '#5b54e9')}
function emptyRow(n,msg){return `<tr><td colspan="${n}" class="empty">${msg}</td></tr>`}function esc(v){return String(v).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function renderProducts(){let q=$('#productSearch').value.toLowerCase(),cat=$('#categoryFilter').value,sort=$('#sortProducts').value,products=db.products.filter(p=>(!q||p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q))&&(!cat||p.category===cat));products.sort((a,b)=>sort==='stock'?a.stock-b.stock:sort==='profit'?(b.sell-b.buy)-(a.sell-a.buy):a.name.localeCompare(b.name));$('#productTable').innerHTML=products.map(p=>`<tr><td class="product-name">${esc(p.name)}</td><td class="muted">${esc(p.category)}</td><td><span class="badge ${status(p)}">${p.stock} units</span></td><td>${money(p.buy)}</td><td>${money(p.sell)}</td><td>${((p.sell-p.buy)/p.buy*100).toFixed(1)}%</td><td><div class="action-row"><button class="action-btn" onclick="editProduct('${p.id}')">Edit</button><button class="action-btn delete" onclick="deleteProduct('${p.id}')">Delete</button></div></td></tr>`).join('')||emptyRow(7,'No products match your filters.');let cats=[...new Set(db.products.map(p=>p.category))];let select=$('#categoryFilter'),old=select.value;select.innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join('');select.value=old}
function renderSaleOptions(){let select=$('#saleProduct'),old=select.value;select.innerHTML='<option value="">Select a product</option>'+db.products.filter(p=>p.stock>0).map(p=>`<option value="${p.id}">${esc(p.name)} — ${p.stock} in stock</option>`).join('');select.value=old;let sales=db.sales,month=sales.filter(s=>s.date.slice(0,7)===today().slice(0,7));$('#salesAtGlance').innerHTML=[['Today’s sales',sales.filter(s=>s.date.slice(0,10)===today()).length],['This month revenue',money(month.reduce((a,s)=>a+s.revenue,0))],['This month profit',money(month.reduce((a,s)=>a+s.profit,0))]].map(x=>`<div class="mini-stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$('#salesTable').innerHTML=sales.slice().reverse().map(s=>`<tr><td class="muted">${dateStr(s.date)}</td><td class="product-name">${esc(s.productName)}</td><td>${esc(s.customer||'Walk-in')}</td><td>${s.quantity}</td><td>${money(s.revenue)}</td><td>${money(s.profit)}</td></tr>`).join('')||emptyRow(6,'No sales recorded yet.')}
function renderInventory(){['out','low','healthy'].forEach(kind=>{let ps=db.products.filter(p=>status(p)===kind),id=kind==='out'?'out':kind==='low'?'low':'healthy';$(`#${id}Count`).textContent=ps.length;$(`#${id}List`).innerHTML=ps.length?ps.map(p=>`<div class="stock-item"><strong>${esc(p.name)}</strong><span>${p.stock} units · ${esc(p.category)}</span></div>`).join(''):'<p class="empty">Nothing here — looking good.</p>'})}
function daySales(){return db.sales.filter(s=>s.date.slice(0,10)===today())}function renderDaily(){let sales=daySales(),rev=sales.reduce((a,s)=>a+s.revenue,0),pro=sales.reduce((a,s)=>a+s.profit,0),qty=sales.reduce((a,s)=>a+s.quantity,0);$('#dailyDate').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});$('#voucherDate').textContent=$('#dailyDate').textContent;$('#dailyStats').innerHTML=[['Today’s revenue',money(rev)],['Today’s profit',money(pro)],['Products sold',sales.length],['Quantity sold',qty]].map(x=>`<div class="voucher-stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');$('#dailySalesTable').innerHTML=sales.map(s=>`<tr><td>${esc(s.productName)}</td><td>${s.quantity}</td><td>${money(s.revenue)}</td><td>${money(s.profit)}</td></tr>`).join('')||emptyRow(4,'No sales today.')}
function daysData(){let labels=[],revenue=[],profit=[];for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);let k=d.toISOString().slice(0,10),s=db.sales.filter(x=>x.date.slice(0,10)===k);labels.push(d.toLocaleDateString(undefined,{weekday:'short'}));revenue.push(s.reduce((a,x)=>a+x.revenue,0));profit.push(s.reduce((a,x)=>a+x.profit,0))}return{labels,revenue,profit}}
function makeChart(id,labels,data,label,color){let canvas=$('#'+id);if(charts[id])charts[id].destroy();if(window.Chart){charts[id]=new Chart(canvas,{type:'line',data:{labels,datasets:[{label,data,borderColor:color,backgroundColor:color+'18',fill:true,tension:.4,pointRadius:3}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,grid:{color:'rgba(125,129,144,.12)'},ticks:{callback:v=>money(v)}},x:{grid:{display:false}}}}})}else{let c=canvas.getContext('2d'),w=canvas.width=canvas.clientWidth*2,h=canvas.height=460;c.clearRect(0,0,w,h);let max=Math.max(...data,1),pad=50;c.strokeStyle=color;c.lineWidth=5;c.beginPath();data.forEach((v,i)=>{let x=pad+i*(w-pad*2)/(data.length-1),y=h-pad-(v/max)*(h-pad*2);i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()}}
function renderMonthly(){let d=daysData(),m=db.sales.filter(s=>s.date.slice(0,7)===today().slice(0,7));$('#monthLabel').textContent=new Date().toLocaleDateString(undefined,{month:'long',year:'numeric'});$('#monthlyStats').innerHTML=[['Monthly revenue',money(m.reduce((a,s)=>a+s.revenue,0)),'↗','var(--primary)'],['Monthly profit',money(m.reduce((a,s)=>a+s.profit,0)),'◉','var(--green)'],['Products sold',m.reduce((a,s)=>a+s.quantity,0),'◈','var(--orange)']].map(x=>`<div class="stat-card" style="--stat-color:${x[3]}"><span class="stat-icon">${x[2]}</span><div class="stat-label">${x[0]}</div><div class="stat-value">${x[1]}</div></div>`).join('');makeChart('revenueChart',d.labels,d.revenue,'Revenue','#5b54e9');makeChart('profitChart',d.labels,d.profit,'Profit','#18a36b')}
function render(){renderDashboard();renderProducts();renderSaleOptions();renderInventory();renderDaily();renderMonthly();$('#darkSetting').checked=db.settings.dark;$('#currencySelect').value=db.settings.currency}
function openModal(p){$('#productModal').classList.add('show');$('#productForm').reset();$('#productModalTitle').textContent=p?'Edit product':'Add product';if(p){$('#editProductId').value=p.id;$('#productName').value=p.name;$('#productCategory').value=p.category;$('#productStock').value=p.stock;$('#buyPrice').value=p.buy;$('#sellPrice').value=p.sell}profitPreview()}
window.editProduct=id=>openModal(productById(id));window.deleteProduct=id=>{let p=productById(id);if(confirm(`Delete ${p.name}? Sales history will be kept.`)){db.products=db.products.filter(p=>p.id!==id);save();render();toast('Product deleted')}};
function profitPreview(){let b=+$('#buyPrice').value,s=+$('#sellPrice').value;$('#profitUnit').textContent=b||s?money(s-b):'—';$('#profitPercent').textContent=b?`${((s-b)/b*100).toFixed(1)}%`:'—'}
$('#productForm').addEventListener('submit',e=>{e.preventDefault();let id=$('#editProductId').value,p={id:id||crypto.randomUUID(),name:$('#productName').value.trim(),category:$('#productCategory').value.trim(),stock:+$('#productStock').value,buy:+$('#buyPrice').value,sell:+$('#sellPrice').value};if(p.sell<p.buy&&!confirm('Sell price is lower than buy price. Save anyway?'))return;if(id)db.products=db.products.map(x=>x.id===id?p:x);else db.products.push(p);save();$('#productModal').classList.remove('show');render();toast(id?'Product updated':'Product added')});
$('#saleForm').addEventListener('submit',e=>{e.preventDefault();let p=productById($('#saleProduct').value),q=+$('#saleQuantity').value;if(!p)return toast('Choose a product first');if(q>p.stock)return toast(`Only ${p.stock} units are in stock`);p.stock-=q;db.sales.push({id:crypto.randomUUID(),productId:p.id,productName:p.name,quantity:q,customer:$('#customerName').value.trim(),revenue:q*p.sell,profit:q*(p.sell-p.buy),date:new Date().toISOString()});save();e.target.reset();$('#salePreview').textContent='Select a product to preview this sale.';render();toast('Sale saved — stock updated')});
function salePreview(){let p=productById($('#saleProduct').value),q=+$('#saleQuantity').value||0;$('#salePreview').textContent=p&&q?`${q} × ${p.name} · Revenue ${money(q*p.sell)} · Profit ${money(q*(p.sell-p.buy))}`:'Select a product to preview this sale.'}
$$('.nav-link[data-page]').forEach(b=>b.onclick=()=>nav(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));$('#menuToggle').onclick=()=>$('#sidebar').classList.toggle('open');$('#quickAdd').onclick=()=>openModal();$('#openProductModal').onclick=()=>openModal();$('[data-close]').onclick=()=>$('#productModal').classList.remove('show');$('#productModal').onclick=e=>{if(e.target.id==='productModal')e.currentTarget.classList.remove('show')};['buyPrice','sellPrice'].forEach(id=>$('#'+id).oninput=profitPreview);['productSearch','categoryFilter','sortProducts'].forEach(id=>$('#'+id).oninput=renderProducts);$('#saleProduct').onchange=salePreview;$('#saleQuantity').oninput=salePreview;
function setTheme(on){db.settings.dark=on;document.body.classList.toggle('dark',on);$('#themeToggle').textContent=on?'☀':'☾';save();render()}$('#themeToggle').onclick=()=>setTheme(!db.settings.dark);$('#darkSetting').onchange=e=>setTheme(e.target.checked);$('#currencySelect').onchange=e=>{db.settings.currency=e.target.value;save();render();toast('Currency updated')};$('#printReport').onclick=()=>window.print();$('#exportPdf').onclick=()=>{window.print();toast('Choose “Save as PDF” in the print dialog')};$('#exportData').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download=`stockly-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup downloaded')};$('#importData').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{try{let v=JSON.parse(r.result);if(!Array.isArray(v.products)||!Array.isArray(v.sales))throw 0;db={...v,settings:{currency:'$',dark:false,...v.settings}};save();setTheme(db.settings.dark);toast('Backup restored')}catch{toast('That file is not a valid Stockly backup')}};r.readAsText(f)};
$('#todayLabel').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});setTheme(db.settings.dark);render();
